import type { Metadata } from 'next'
import { Inter ,Outfit} from 'next/font/google'
import './globals.css'
import { ClerkProvider, SignIn, SignedIn, SignedOut } from '@clerk/nextjs'
import NavBar from '@/components/NavBar'

const outfit = Outfit({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={outfit.className}>
        <SignedIn>
          <NavBar/>
        {children}
        </SignedIn>
        <SignedOut>
          <SignIn/>
        </SignedOut>
        </body>
    </html>
    </ClerkProvider>
  )
}
